language: csharp
sudo: required
dist: trusty
mono: latest
dotnet: 1.0.3

branches:
  only:
  - master

before_script:
  - ./build.sh --target Restore-Solution

script:
  - ./build.sh --target Run-Test 
  - ./build.sh --target Publish-NuGet