language: csharp
sudo: required
dist: trusty
mono: latast
dotnet: 1.0.3

branches:
  only:
  - master

before_script:
  - ./build.sh --target Restore-Solution

script:
  - ./build.sh --target Test-Project 
  - ./build.sh --target Publish-NuGet